### ISSUE TITLE
hit q to exit

### ISSUE THREAD

**Issue by thomas-mc-work** [Emanem/nettop#1]
It would be nice to be able to exit the tool by hitting the <kbd>q</kbd> button (which is quite common in such linux tools).

**Comment by Emanem** [comment]
Agreed, should work on that!
... or you can do it and raise a pull request! :)

**Comment by Emanem** [comment]
If I may suggest, I would go for an implementation where in the main loop one uses _epoll_ on _stdin_ instead of the the `std::this_thread::sleep_for(std::chrono::milliseconds(sleep_interval));` to check for character such as `'q'`. That patch I would accept! :+1:

**Comment by Emanem** [comment]
Just implemented a patch to do the above. ESC will also close it.
