### ISSUE TITLE
Add version tag or release

### ISSUE THREAD

**Issue by Hellseher** [Emanem/nettop#14]
Hi,

I'm in review process of preposal to include this project to Guix package index,
but it does not contain any version tag or release. Having them may help to address issues 
and impove user experiance for end users.

Do you have any plan to add it?

- https://issues.guix.gnu.org/73606

Thanks,
Oleg

**Comment by Emanem** [comment]
Hi Oleg, I don't maintain that mirror?
If it's something related to the core feel free to send a PR.

**Comment by Hellseher** [comment]
Hi @Emanem 

Thank you for your attention.

I'm not sure I can submint a PR adding version tag or release :-)
