### ISSUE TITLE
nettop exits when window is resized on i3

### ISSUE THREAD

**Issue by okubax** [Emanem/nettop#4]
Hi, with the latest commit https://github.com/Emanem/nettop/commit/b79390c7886b85b5b601bcebbff8886e1f9d6907 , on i3wm, the nettop program exits when its windows is resized. This started happening when I pulled and ran with the aforementioned commit

Error shown is:

```
Exception: Error in epoll_wait: Interrupted system call
```

**Comment by Emanem** [comment]
Thanks for the feedback - looks like it should be managing better epoll return codes when it's interrupts and not _real_ errors!

**Comment by Emanem** [comment]
@okubax Please test the latest head - it should fix this issue.
