### ISSUE TITLE
Add an option '-n' to disable resolving of addresses

### ISSUE THREAD

**Issue by ghost** [Emanem/nettop#5]
Can you add an option '-n' to disable resolving of addresses?
It is helping to show ip addresses instead of host name,
thank you.

**Comment by Emanem** [comment]
Why not? Seems a reasonable request, will do over the coming days... :-)

**Comment by Emanem** [comment]
@jones-tw Please switch over to branch "0.5", compile and test it and let me know if you face any issue.

If no issues are found, I'll merge to _master_ later on.

**Comment by ghost** [comment]
Hello @Emanem 

'-n' looks great to me! 
Switch to branch "0.5" & compile & test without issues, Thank you!

![nettop_n](https://user-images.githubusercontent.com/55226393/84844424-dee1e180-b07c-11ea-9a9f-6585ceb2718a.png)

**Comment by Emanem** [comment]
Very good, merging into master then!
